### ISSUE TITLE
Improve backwards compatibility of changes in the templates

### ISSUE THREAD

**Issue by bwl21** [voidlabs/mosaico#65] opened 2015-11-30 17:45 UTC
In the tutorial I try to add a new property: color. I updated my template

```html
    <style type="text/css">
        @supports
            -ko-blockdefs {
                 color {widget: color;}
        }
    </style>

...
 <div data-ko-block="fixedlist" style="background-color: #f0f0f0; -ko-background-color: @color;">
```

But when I load an existing Email (as discussed, i load the JSON from local store), I get

```
Trying to compile an incompatible template version!templateCompiler @ mosaico.min.js?v=0.11:1314(anonymous function) @ mosaico.min.js?v=0.11:1314j @ jquery.min.js:2k.fireWith @ jquery.min.js:2x @ jquery.min.js:5b @ jquery.min.js:5
mosaico.min.js?v=0.11:1293 Uncaught TypeError: Cannot read property 'color' of null
````

Reason is, that the save model does not provide a value for 'color';

Is there any chance to overcome this such that one can still load emails created with an earlier template.

**Comment by bago** [comment] 2015-11-30 18:06
I can't think at an easy way fo deal with this.

**Comment by bago** [comment] 2015-11-30 18:48
Thinking more about this, maybe one way would be to take the model from the template then merge the loaded model over it, then check compatibility... but this would probably "hide" some critical update compatibility path.

So, instead of taking the "loaded template" "as is" and check the compatibility, we could extend the "base template" with the "loaded template". But this also needs some "intelligence" to make single block extensions (this needs to know how mainBlocks works as it would not be a simple object extension).

**Comment by bwl21** [comment] 2015-11-30 18:50
Wouldn't it be possible to provide a default value:

```
            -ko-blockdefs {
                 color {
                    widget: color;
                    default: #0f0f0f;
            }
```

In this case the template author could support backwards compatibility.

**Comment by bago** [comment] 2015-11-30 19:50
This is not about default values. Default values are there and you are already setting a default value when you do "style="background-color: #f0f0f0; -ko-background-color: @color;"   #f0f0f0  IS the default value for the color property.


In fact if you do "style="background-color: #f0f0f0; -ko-background-color: @color;"" and then "style="background-color: #cccccc; -ko-background-color: @color;" the compiler will complain because you can't have 2 different default values for the same property.

Your issue is just about loading a saved template that doesn't care at all about those default values.

**Comment by bwl21** [comment] 2015-12-01 10:41
Ok, I renamed the issue. I will open another one with respect to default values.

**Comment by psyafter** [comment] 2015-12-04 14:00
What about checking that all options (types) from loaded template are really exists in model template?
if not exists - so template "broken", but if there are new options in real template that not exists in saved template - so it's just ok and marked as "compatible"...

**Comment by psyafter** [comment] 2015-12-04 14:19
@bwl21 btw - how you store and restore data?
I tried to add new types with using them in template, and my saved template loaded without errors...

I'm save following data:
var mymetadata = viewModel.exportMetadata()
var mycontent = viewModel.exportJSON()

and restore it:
var plugins = [
	function (vm) {
		window.viewModel = vm;
	}
];
mosaicoConfig.data = {
	metadata: mymetadata,
	content: ko.utils.parseJson(mycontent)
};
Mosaico.init(mosaicoConfig, plugins);

**Comment by bwl21** [comment] 2015-12-04 14:24
I still use the localStorage. I would like to do it on the backend but my JS skills are not such that I find my way through the issue.

I find that storage is distributed between index.html / editor.html and Mosaico. I hope we find a better structure:

* only one HTML - file
* Mosaico can be embedded so there is no need for an extra editor.html
* do save and load etc. outside of Mosaico, maybe by plugins (even if I did not fully understand how to write/use/remove the plugins)

**Comment by bago** [comment] 2015-12-05 12:35
You are a bit OT in the last comments.

Please note that content-model compatibility is checked by "src/js/converter/checkmodel.js". This methods takes as input the block definitions, the template-defined base-content-model and the input content-model and check the compatibility level:
```
// returns 0 if equal (0.0.x release), 1 with backward compatible additions (0.x.0 release), 2 on lost data or incompatible data (x.0.0 release)
```

So, can you tell me what kind of console.log did you see when you received the "Trying to compile an incompatible template version!" error?

This way we can evaluate if checkModel can automatically "fix" (update) the content-model instead of logging an error, or if we don't have enough informations for doing that (you can see there are already automcatic-fixes being handled there).

**Comment by bwl21** [comment] 2015-12-05 12:41
I agree with OT, I plan to write Issue about storing later today.

You see the console message in the opening message. I will try to reproduce the issue and see if there are more details

**Comment by bwl21** [comment] 2015-12-05 15:40
1. Checkout 832ce7f
2. create a newsletter based on tutorial, add at least the list block, push "save" in Editor
![screenshot_414](https://cloud.githubusercontent.com/assets/2022976/11608605/6a625e16-9b6e-11e5-8b31-866c086e128a.jpg)

3. Checkout 94fa74f
4. (try to) restore the newsletter based on tutorial

chrome console yields
```
Trying to compile an incompatible template version!templateCompiler @ mosaico.min.js?v=0.11:1314(anonymous function) @ mosaico.min.js?v=0.11:1314j @ jquery.min.js:2k.fireWith @ jquery.min.js:2x @ jquery.min.js:5b @ jquery.min.js:5
mosaico.min.js?v=0.11:1293 Uncaught TypeError: Cannot read property 'color' of null_makeComputedFunction @ mosaico.min.js?v=0.11:1293_makeComputedFunction @ mosaico.min.js?v=0.11:1293f @ mosaico.min.js?v=0.11:27l @ mosaico.min.js?v=0.11:27t.fromJS @ mosaico.min.js?v=0.11:27_blockInstrumentFunction @ mosaico.min.js?v=0.11:1293_wrap @ mosaico.min.js?v=0.11:1293templateCompiler @ mosaico.min.js?v=0.11:1314(anonymous function) @ mosaico.min.js?v=0.11:1314j @ jquery.min.js:2k.fireWith @ jquery.min.js:2x @ jquery.min.js:5b @ jquery.min.js:5
```

**Comment by bago** [comment] 2015-12-06 16:25
It's weird you don't have any other console log as the "Trying to compile an incompatible template version!" happens only when checkModel returns 2 and every condition where checkModel returns 2 hase a console.log just before... BTW if you don't see more logs I will try to reproduce it once I have some time.

**Comment by bwl21** [comment] 2015-12-06 16:28
I will reproduce it and post every log I can find ...

**Comment by psyafter** [comment] 2015-12-07 08:17
@bago what about exporting template html to local storage and restore it with meta and content data?
by this way there is will no more dependency between real physical template (that can be changed/improved) and saved template. so owner of template can change and not worry about  all saved users emails. saved email template will not break never! and it will be always consistently with started  template. i don't know why user email template must rely on physical template. one he started email - he will always work with his copy and not rely on real template that can be changed and will break his work.

**Comment by bwl21** [comment] 2015-12-07 08:20
One of the coolest features of mosaico, is that updated of the template (e.g. style) applies to newsletters (emails) when they are reloaded. This would go away if you store a snapshot of the template together with the email. This approach would provide a fallback position if compatibility is broken such that it cannot be fixed.

**Comment by bago** [comment] 2015-12-07 09:01
the generated HTML doesn't contain all of the metadata we need to instantiate mosaico. That's the master-template. 

If you want to introduce a new template version with NON-BACKWARD-compatibility changes then simply make a new template a let new users use the new template while your old users still will be able to open old content done with the old template.

We are using this "plan" already in production and it worked fine: that's why I introduced a "checkModel" that tells you if a content is compatibile with the current template, so when you develop you get an hint that you broke stuff and you better create a new template.

You know, versafix-1 is named this way because it is an incompatible version of the "versafix" template, an older template that I didn't opensource and was the ancestor of versafix-1. You know I updated a lot versafix-1 html to introduce client-specific hacks but I kept content-model compatibility so this was cool. If I'll ever need to change the content-model then I'll create a versafix-2 and leave versafix-1 around for old contents.

You solution would be to save the whole master template for each export so that it is "standalone" but it sounds overkill. (the master template contains the definitions, images and much more that cannot be found in the exported html).

**Comment by bago** [comment] 2015-12-07 09:03
Mosaico doesn't ever import HTML: mosaico doesn't even understand the HTML it exports. The only way to let mosaico import back an exported HTML would be to save all of the stuff we have in the master-template (all of the template language stuff, the bundled images, the thumbnails and so on).

**Comment by psyafter** [comment] 2015-12-07 09:36
of course I told about master template html, not clear html that ready to sending.
There is any option in "init" that can get master template html instead of link to physical template and load it from there? (premise is that images in template can't be changed but only added new for next improved versions of same template)

**Comment by bwl21** [comment] 2015-12-07 09:36
I did the sequence again:

This is the browser log:

![screenshot_416](https://cloud.githubusercontent.com/assets/2022976/11623607/58f41ba4-9cce-11e5-8c54-d3639606621d.jpg)

![screenshot_417](https://cloud.githubusercontent.com/assets/2022976/11623605/56d86bae-9cce-11e5-954c-b0486ab2cace.jpg)

**Comment by bwl21** [comment] 2015-12-07 09:43
I still think it is one of the (many) cool features of mosaico to update a template and reload emails based on an earlier version. 

As of now the template does not allow to preliminary create an email and insert blocks automatically. But this can be overcome by an approach to save Samples of various emails which are based on the same template. Creating a new email would then not start with the template but with the sample. But all these samples would go away if there is now migration path between template versions.

**Comment by bago** [comment] 2015-12-07 09:52
As I said, we already have a function to try to update outdated content-models (checkModel.js).
The last 4 TODO from your console are from that method and give us pointers about where to improve the code in order to deal with this kind of content "upgrade".

No time right now to do this, but it shouldn't be hard.

The 3 console logs are from here, and I think this one is the place to be enhanced:
https://github.com/voidlabs/mosaico/blob/master/src/js/converter/checkmodel.js#L94

The first line comes from here but it is an "1" (incompatible but upgradable) so I think it is already handled.
https://github.com/voidlabs/mosaico/blob/master/src/js/converter/checkmodel.js#L24

**Comment by bago** [comment] 2015-12-07 10:07
One of the logs is from here, too:
https://github.com/voidlabs/mosaico/blob/master/src/js/converter/checkmodel.js#L87

From a fast overview we have to add an "if (!reverse) model[prop] = reference[prop];" in that line 87 and an "if (!reverse)" condition to the https://github.com/voidlabs/mosaico/blob/master/src/js/converter/checkmodel.js#L93 because that check makes no sense when "reversed".

But I have to go now...

**Closed** 2015-12-07 16:08 UTC
Labels: enhancement

**Comment by love-kush** [comment] 2019-04-16 10:57
please provide me background image block
