### ISSUE TITLE
Button not more editable after deleting whole text (if bold)

### ISSUE THREAD

**Issue by morloi** [voidlabs/mosaico#212] opened 2016-09-22 08:59 UTC
Hi, I've found that in webkit based browsers (Chrome and Safari, so far), if you make the whole button text **bold**, then you select it all and delete it, you'll won't be able to edit it no more:
in Chrome it will accept only 1 char, even if you select something else and come back to button
in Safari it will show for a moment 1 char, then none. If you select something else and come back, the button will be again editable.

**Comment by bago** [comment] 2016-09-22 09:03
So, this happens on versafix-1. I guess it is "markup specific" and it depends on contenteditable bugs in webkit or in tinymce workarounds for them.

**Comment by bago** [comment] 2016-09-22 09:05
Here is a fiddle to check the issue.
http://fiddle.tinymce.com/17faab

It seems the issue is fixed in tinymce since 4.4.0
I checked this on Windows Chrome: can you check this with Safari and report back?

**Comment by bago** [comment] 2016-09-22 09:36
Back from some fiddle testing...

Chrome 53 on Windows and Linux is fixed by tinymce 4.4.0
Chrome 52 and 53 and Safari 9.1.3 on Mac OS X is NOT fixed by newer tinymce.

It seems that introducing an editable span element instead of editing the a tag, fixes it on mac os.. but it requires hacks/changes to the templates (or workarounds in mosaico so to add markup that could create other issues...)

**Comment by bago** [comment] 2016-09-22 13:10
https://github.com/tinymce/tinymce/issues/3222

**Closed** 2016-10-07 15:35 UTC
Labels: bug

**Comment by Vgratioulet** [comment] 2018-03-16 08:38
Hello, it's happening also in Firefox 52/Debian and Firefox 59/Ubuntu, even if I don't put the text in bold 
reproduced on https://mosaico.io/editor-0.17.4.html

**Comment by bago** [comment] 2018-03-16 10:00
@Vgratioulet if it happens in Firefox and without bold then it doesn't sounds like the same issue... 

This bug reference the https://github.com/tinymce/tinymce/issues/3222 issue and a fiddle http://fiddle.tinymce.com/17faab/3 : can you reproduce the  same issue in the fiddle? (in that fiddle you can test any tinymce version, so if you see the issue please test the other versions and tell us which versions reproduce the issues and which are working fine).

If you can't reproduce it in the fiddle then it is not the same bug, so open a new issue and describe the steps you do and what it does happen. Tell us if it happens only on specific fields or every title, every paragraph, every button.

**Comment by Vgratioulet** [comment] 2018-03-16 10:35
you're right, it does work in the fiddle in tinymce 4.58 and 3.4.5, when I remove everything I can still find the focus on the field and type again. I opened a new issue #426
