### ISSUE TITLE
Bug: Getting Wrong query string via php, java, nodejs

### ISSUE THREAD

**Issue by frank-dspeed** [voidlabs/mosaico#255] opened 2016-12-21 13:29 UTC
Will Only show php:

http://172.17.0.4/index.php?method=placeholder&params=166%2C130
```
Array
(
    [UNIQUE_ID] => WFqAZ6naoyAiTd3CkBb8aAAAAAA
    [HTTP_HOST] => 172.17.0.4
    [HTTP_CONNECTION] => keep-alive
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
    [HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache/2.4.6 (CentOS) PHP/5.4.16
    [SERVER_NAME] => 172.17.0.4
    [SERVER_ADDR] => 172.17.0.4
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 172.17.0.1
    [DOCUMENT_ROOT] => /var/www/html
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/html
    [SERVER_ADMIN] => root@localhost
    [SCRIPT_FILENAME] => /var/www/html/index.php
    [REMOTE_PORT] => 35252
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => method=placeholder¶ms=166%2C130
    [REQUEST_URI] => /index.php?method=placeholder¶ms=166%2C130
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1482326119.928
    [REQUEST_TIME] => 1482326119
)
```

gets fixed via pull request #252 

Bug Happens not with curl but with chrome 54+ firefox current + safari

**Comment by frank-dspeed** [comment] 2016-12-21 13:39
Request with firefox current
```
Array
(
    [UNIQUE_ID] => WFqF2MQObue6DL3yInFhAwAAAAU
    [HTTP_HOST] => 172.17.0.4
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
    [HTTP_ACCEPT_ENCODING] => gzip, deflate
    [HTTP_CONNECTION] => keep-alive
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache/2.4.6 (CentOS) PHP/5.4.16
    [SERVER_NAME] => 172.17.0.4
    [SERVER_ADDR] => 172.17.0.4
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 172.17.0.1
    [DOCUMENT_ROOT] => /var/www/html
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/html
    [SERVER_ADMIN] => root@localhost
    [SCRIPT_FILENAME] => /var/www/html/index.php
    [REMOTE_PORT] => 35966
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => method=placeholder¶ms=166%2C130
    [REQUEST_URI] => /index.php?method=placeholder¶ms=166%2C130
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1482327512.973
    [REQUEST_TIME] => 1482327512
)
```

**Comment by bago** [comment] 2016-12-21 14:08
Can you please print also the "$_GET" variable?
Can you also show me an url passing as the query string parameter "param" the value "me+you" ?

**Comment by frank-dspeed** [comment] 2016-12-21 14:39
@bago in short terms its to enforce UTF-8 Compatiblity it gets used in many applications to enforce UTF-8

but in your case its not needed as the browser gets accept encoding headers and encodes the url right 
as also the ajax jquery function gets the accept encoding headers and does that 

hope that makes sense

**Comment by bago** [comment] 2016-12-21 14:43
Can you please print also the "$_GET" variable?
Can you also show me an url passing as the query string parameter "param" the value "me+you" ?

**Comment by frank-dspeed** [comment] 2016-12-21 15:16
The GET Array looks working so there the corrections happen. in this case
so we found out that php $_GET array has some methods in it to correct the string.
```
Array
(
    [method] => placeholder
    [params] => 534,200
)
```

**Comment by frank-dspeed** [comment] 2016-12-21 15:20
@bago and encode uri converts + to %2b because thats the utf expression of it :)

http://www.endmemo.com/unicode/unicodeconverter.php enter there a +


UTF-8 Code = 2B
Escaped Unicode = /u2B

**Comment by frank-dspeed** [comment] 2016-12-21 15:22
@bago anyway such converting things if done in your script leads to fails on servers that recive that things and depend on other values then you expect thats why encoding headers are always importent if you set encoding on values.

**Comment by frank-dspeed** [comment] 2016-12-21 15:26
@bago alternativ to this fix is to simply read out the current used browser encoding :) and then encode with that but i think the browser does that already realy well based on local settings.

**Comment by frank-dspeed** [comment] 2016-12-21 15:31
```
Array
(
    [method] => placeholder
    [params] => me you
)
Array
(
    [REDIRECT_UNIQUE_ID] => WFqgCtmIrdA4oiriedTOtwAAAAQ
    [REDIRECT_STATUS] => 200
    [UNIQUE_ID] => WFqgCtmIrdA4oiriedTOtwAAAAQ
    [HTTP_HOST] => 172.17.0.4
    [HTTP_CONNECTION] => keep-alive
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
    [HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache/2.4.6 (CentOS) PHP/5.4.16
    [SERVER_NAME] => 172.17.0.4
    [SERVER_ADDR] => 172.17.0.4
    [SERVER_PORT] => 80
    [REMOTE_ADDR] => 172.17.0.1
    [DOCUMENT_ROOT] => /var/www/html
    [REQUEST_SCHEME] => http
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/html
    [SERVER_ADMIN] => root@localhost
    [SCRIPT_FILENAME] => /var/www/html/index.php
    [REMOTE_PORT] => 41330
    [REDIRECT_QUERY_STRING] => method=placeholder¶ms=me+you
    [REDIRECT_URL] => /img/
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => method=placeholder¶ms=me+you
    [REQUEST_URI] => /img/?method=placeholder¶ms=me+you
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1482334218.989
    [REQUEST_TIME] => 1482334218
)
```

**Comment by bago** [comment] 2016-12-21 17:42
"@bago and encode uri converts + to %2b because thats the utf expression of it :)"
Don't joke me: it doesn't convert A to %41, so it is not about UTF8 but it is about special chars.

If you want to pass a string as a "query parameter" then you have to "url encode the component": this is what your PHP dump "confirm" so now I'm not anymore the only one that disagree with you, beucase also PHP disagree with you when it deals with the _GET array (that is the way php expose to you query variables).

So, we build that url and that url have to pass 3 parameters and when you do this you are expected to call encodeUriComponent on each parameter value otherwise you will also have situations where an incoming parameter will not reach the server as intended.

If you don't call encodeUriComponent then your "+" will break. So I don't see how this can be considered a bug. The dumps you reported are exactly the dumps I know and I expected.. there is nothing here that "prove" the presence of a bug, IMO.

I close this bug report because I don't really see issues.

If you write a backend in PHP you are expected to read $_GET['method'] and $_GET['params'] and they contains a correct value. Here I don't see anything that is not "RFC compliant".

**Closed by bago** 2016-12-21 17:42 UTC

**Comment by bago** [comment] 2016-12-21 17:48
The way to make sure $_GET['param'] will be received correctly is to do call the url 
```javascript
var url = 'http://host/path?param='+encodeURIComponent(value);
```

if you don't write that "encodeURIComponent" than your $_GET['param'] will contain a differnt value than you had in "value" whenever an "=", "&", "+", "%20" or other % sequence is contained in your original value.

Hope you get this.
