### ISSUE TITLE
Linked buttons do not work properly in Outlook Webapp

### ISSUE THREAD

**Issue by tjernicJC** [voidlabs/mosaico#539] opened 2019-08-02 10:35 UTC
The Links behind the Buttons are displayed and do not work when looking at the E-Mail in the Office 365 Outlook Webapp. 

In the other Mail Apps it works perfectly, it just doesn't in the Webapp. 
I used the versafix-1 template on mosaico.io

![Unbenannt](https://user-images.githubusercontent.com/53607603/62364265-53716780-b521-11e9-895a-b2b38111e96f.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/53607603/62364266-53716780-b521-11e9-89d1-ece18cc71129.PNG)

**Comment by bago** [comment] 2019-08-16 11:37
I can't reproduce this issue.
Please attach your full html.

**Comment by bago** [comment] 2019-09-26 09:39
no answers, closing.

**Closed by bago** 2019-09-26 09:39 UTC
