### ISSUE TITLE
bug in title tags on any content block (tinymce)

### ISSUE THREAD

**Issue by jrodri-ariad** [voidlabs/mosaico#151] opened 2016-05-26 18:40 UTC
Hi,

I have discovered a bug that I have no idea how to troubleshoot and though someone could help me with.

The bug occurs on versafix template, when editing any of the title tags on any content block.

To reproduce:
1.- Install a fresh copy of mosaico following the instructions in the readme file.
2.- After grunt has launched the local instance of mosaico, drag a block that contains a title tag (any)
3.- Select the title, select all the contents, and start typing, you will notice that the first character typed it not inserted, and there is an error in the console:
`tinymce.min.js:4 Uncaught TypeError: Cannot read property 'firstChild' of null`

Thanks.

**Comment by keneasson** [comment] 2016-05-26 21:09
I am able to reproduce this error on a brand new installation of Mosaic. However i noted this does not occur on the Mosaico demo on the Mosaico site. 
The difference i noted is that the version i have installed uses TinyMCE // 4.3.12 (2016-05-10) while the Mosaico site is using TinyMCE // 4.1.7 (2014-11-27)

**Comment by bago** [comment] 2016-05-27 07:38
I'm sorry I can't reproduce it. What browser/browsers did you test? Do you see the same bug in all of them?

What is the specific block/content where you reproduce the issue?

How do you "select-all"? Double clicking? CTRL+A? Dragging with the mouse? CTRL+SHIFT + RIGHT/LEFT arrows? Does the way you select, influences the bug?

Do you see the same issue in this fiddle?:
http://fiddle.tinymce.com/zyfaab

**Comment by jrodri-ariad** [comment] 2016-05-27 12:56
Hi @bago,

I was trying mainly with Chrome. 

The issue happens when double clicking to select all the text or when using the mouse drag to select all the text... actually, not all the text has to be selected, after any selection is made with the mouse or keyboard then the first letter typed is obviated.

Thanks for the fiddle, this bug happens there too, on the span tag only, the div works fine.

Anyways, I think is safe to say that this is not a Mosaico bug, but a TinyMCE one, although Mosaico is obviously affected by it. I will report this bug to TinyMCE...

Also, I noticed that this error doesn't occur in Mosaico's live demo, probably because a older version of tinyMCE is used there as @keneasson pointed out.

As always, Thanks for your help.

**Comment by bago** [comment] 2016-05-27 13:33
Thank you for the link! Weird thing is that I cannot reproduce it with my Chrome on my fiddle.

**Comment by bago** [comment] 2016-11-08 08:55
Hi @jrodri-ariad can you check the above fiddle again and see if the latest tinymce still show the same issue to you?

**Comment by jrodri2001** [comment] 2016-11-08 13:28
Hi Bago.

Yes it seems to still be doing the same. To reproduce, I clicked the span text, modified it with some content. then, deselected the span text. After that, double clicked to select all the text in the span area, and typed any letter, the first letter is not typed.

**Comment by bago** [comment] 2016-11-08 13:38
I still can't reproduce it here.. I experienced a similar issue that was fixed by using Tinymce 4.4.x. In my case the issue only happened when the content was formatted (e.g: the whole text was bold).

What's your Browser/OS ? Are you on MacOS X? (I know a similar issue to be reproducible only on MacOS X)

When you say "modified it with some content" do you mean "any content", like writing a simple "a" letter or you have to insert a specific content in order to reproduce it?

**Comment by bago** [comment] 2018-03-27 21:01
Can you check if this still applies with latest code (by downloading latest release or directly testing on https://mosaico.io ?

**Comment by bago** [comment] 2022-04-27 10:16
No answer, I guess this is fixed.

**Closed by bago** 2022-04-27 10:16 UTC
Labels: bug, tinymce
